### ISSUE TITLE
Doesn't handle > 3 columns bed files

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/eggd_region_coverage#3]
Bed files with more than 3 columns are not handled because of this line:
```
Traceback (most recent call last):
  File "/usr/bin/region_coverage.py", line 120, in <module>
    (region_chrom, region_start, region_end, region_region_id) = entry.split("\t")
ValueError: too many values to unpack
```

Suggested fix: `entry.split("\t")[0:4]`

**Comment by sophie22** [comment]
Hi, do you have an example input that breaks the app? I'm in the process of updating it and could try to include other fixes like this.

**Comment by Yu-jinKim** [comment]
You can just have a dummy file with one line and 4 columns
