### ISSUE TITLE
pysam install fails

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_region_coverage#9]
`pip install pysam==0.7.6` now fails, so the app fails

`pip2 install pysam==0.7.6` seems to work, but would need testing within the app

**Comment by jethror1** [comment]
nice example of why we should use local packages, if it's included `pip install local_package` should still work too

**Comment by sophie22** [comment]
There is a new pip version released (v21) which NO LONGER SUPPORTS Python 2!!! solution was to upgrade pip specifically to version 20.3.3
